http_listen = ":8080"
base_url = "http://127.0.0.1:8080/"

[[auth]]
path = [
  "/api/packages/versions/new",
]
token = [
  "bcrypt:$2a$10\\$um0Ts3R4oFERUb.eeQ6PruhcGvK8ETaXNdmz7TykclbpyR4dphNkK",
]
# $2a$10$um0Ts3R4oFERUb.eeQ6PruhcGvK8ETaXNdmz7TykclbpyR4dphNkK
# $2a$10.eeQ6PruhcGvK8ETaXNdmz7TykclbpyR4dphNkK
