version: 2

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        formats: 
          - zip

dockers_v2:
  - images:
      - "ghcr.io/fmotalleb/pub-dev"
    tags:
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    
    labels:
      # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"

release:
  github:
    owner: FMotalleb
    name: pub-dev
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
